"""For SSOT / Dynamic related things."""

groups = ["Moderator", "Sub-moderator"]

# Path and fields name, those field value will be dummy data while saving in log file
sensitive_fields = {
    "/user/registration/": ["password", "confirm_password"],
    "/api/login/": ["password"],
    "/user/reset-password/": ["new_password", "confirm_new_password"],
    "/user/change_password/": [
        "old_password",
        "new_password",
        "confirm_new_password",
    ],
    "/admin-login/": ["password"],
    "/admin/user/user/add/": ["password1", "password2"],
}


# List of url path for which is not required client api key
ALLOWED_PATHS_WITHOUT_CLIENT_API_KEY = [
    "/core/client-api-key/",
    "/core/client-api/"
]

# List of url path for which and their extention is not required client api key
ALLOWED_PATHS_WITH_EXTENSION_WITHOUT_CLIENT_API_KEY = [
    "/admin",
]

# 'ContactUs' model 'attachment' max size
MAX_CONTACT_US_ATTACHMENT_SIZE = 5 * 1024 * 1024  # 5MB

# Max 'PortfolioImage' objects for one 'Portfolio'
MAX_PORTFOLIO_IMAGE_NUMBER = 10

# CHAT MAX FILE SIZE 
MAX_FILE_SIZE_FOR_CHATTING = 5 * 1024 * 1024 # 5MB

# CHAT MAX VOICE DURATION
MAX_VOICE_DURATION_MIN = 2
MAX_VOICE_DURATION_FOR_CHATTING = MAX_VOICE_DURATION_MIN * 60 # 2 MIN

# VOICE MESSAGE LIMIT
MAX_VOICE_MESSAGE_FOR_PER_CHATTING_ROOM = 10

# 'Notification' 'body' field value
ORDER_CREATE_MSG = "An Order has created by {first_name} {last_name}"
ORDER_UPDATE_MSG = "Order has updated by {first_name} {last_name}"

LIST_OF_COUNTRIES_WITH_CURRENCY = [
    ["Afghanistan", "Afghan Afghani", "AFN"],
    ["Albania", "Albanian Lek", "ALL"],
    ["Algeria", "Algerian Dinar", "DZD"],
    ["American Samoa", "United States Dollar", "USD"],
    ["Andorra", "Euro", "EUR"],
    ["Angola", "Angolan Kwanza equals", "AOA"],
    ["Anguilla", "Eastern Caribbean dollar", "XCD"],
    ["Antigua and Barbuda", "East Caribbean Dollar", "XCD"],
    ["Argentina", "Argentine Peso", "ARS"],
    ["Armenia", "Armenian Dram", "AMD"],
    ["Aruba", "Aruban Florin", "AWG"],
    ["Australia", "Australian Dollar", "AUD"],
    ["Austria", "Euro", "EUR"],
    ["Azerbaijan", "Azerbaijan Manat", "AZN"],
    ["Bahamas", "Bahamian Dollar", "BSD"],
    ["Bahrain", "Bahraini Dinar", "BHD"],
    ["Bangladesh", "Bangladeshi Taka", "BDT"],
    ["Barbados", "Barbados Dollar", "BBD"],
    ["Belarus", "Belarusian Ruble", "BYR"],
    ["Belgium", "Euro", "EUR"],
    ["Belize", "Belize Dollar", "BZD"],
    ["Benin", "CFA Franc BCEAO", "CFA"],
    ["Bermuda", "Bermudian Dollar", "BMD"],
    ["Bhutan", "Bhutanese Ngultrum", "BTN"],
    ["Bolivia", "Boliviano", "BOB"],
    ["Bosnia and Herzegovina", "Convertible Mark", "BAM"],
    ["Botswana", "Pula", "BWP"],
    ["Brazil", "Brazilian Real", "BRL"],
    ["Brunei Darussalam", "Brunei Dollar", "BND"],
    ["Bulgaria", "Bulgarian Lev", "BGN"],
    ["Burkina Faso", "CFA Franc BCEAO", "CFA"],
    ["Burundi", "Burundi Franc", "BIF"],
    ["Cambodia", "Cambodian Riel ", "KHR"],
    ["Cameroon", "CFA Franc BEAC", "XAF"],
    ["Canada", "Canadian Dollar", "CAD"],
    ["Cape Verdennn", "Cape Verde Escudo", "CVE"],
    ["Cayman Islands", "Cayman Islands Dollar", "KYD"],
    ["Central African Republic", "CFA Franc BEAC", "XAF"],
    ["Chad", "CFA Franc BEAC", "XAF"],
    ["Chile", "Chilean Peso", "CLP"],
    ["China", "Renminbi (Yuan)", "CNY"],
    ["Christmas Island", "Australian Dollar", "AUD"],
    ["Cocos Islands", "Australian Dollar", "AUD"],
    ["Colombia", "Colombian Peso", "COP"],
    ["Comoros", "Comoro Franc", "KMF"],
    ["Congo, Dem. Republic", "Franc Congolais", "CDF"],
    ["Congo, Republic of", "CFA Franc BEAC", "XAF"],
    ["Cook Islands", "New Zealand Dollar", "NZD"],
    ["Costa Rica", "Costa Rican Colón", "CRC"],
    ["Cote D'Ivoire", "CFA Franc BCEAO", "CFA"],
    ["Croatia/Hrvatska", "Croatian Kuna", "HRK"],
    ["Cuba", "Cuban Peso", "CUP"],
    ["Cyprus", " Northern Cyprus", "EUR"],
    ["Czech Republic", "Czech Koruna", "CZK"],
    ["Denmark", "Danish Kroner", "DKK"],
    ["Djibouti", "Djibouti Franc", "DJF"],
    ["Dominica", "East Caribbean Dollar", "XCD"],
    ["Dominican Republic", "Dominican Peso", "DOP"],
    ["Ecuador", "US Dollar ", "USD"],
    ["Egypt", "Egyptian Pound", "EGP"],
    ["El Salvador", "Salvadoran Colón", "SVC"],
    ["Equatorial Guinea", "CFA Franc BEAC", "XAF"],
    ["Eritrea", "Nakfa", "ERN"],
    ["Estonia", "Estonian Kroon", "EEK"],
    ["Ethiopia", "Ethiopian Birr", "ETB"],
    ["Falkland Islands", "Falkland Islands pound", "FKP"],
    ["Faroe Islands", "Faroese króna ", "FOK"],
    ["Fiji", "Fiji Dollar", "FJD"],
    ["Finland", "Euro", "EUR"],
    ["France", "Euro", "EUR"],
    ["French Guiana", "Euro", "EUR"],
    ["French Polynesia", "CFP Franc", "XPF"],
    ["French Southern Territories", "Euro", "EUR"],
    ["Gabon", "CFA Franc BEAC", "XAF"],
    ["Gambia", "Dalasi", "GMD"],
    ["Georgia", "Lari", "GEL"],
    ["Germany", "Euro", "EUR"],
    ["Ghana", "Cedi", "GHC"],
    ["Gibraltar", "Gibraltar Pound", "GIP"],
    ["Greece", "Euro", "EUR"],
    ["Greenland", "Danish Krone", "DKK"],
    ["Grenada", "East Caribbean Dollar", "XCD"],
    ["Guadeloupe", "Euro", "EUR"],
    ["Guam", "US Dollar", "USD"],
    ["Guatemala", "Quetzal", "GTQ"],
    ["Guinea", "Guinea Franc", "GNF"],
    ["Guinea-Bissau", "Guinea-Bissau Peso", "GWP"],
    ["Guyana", "Guyana Dollar", "GYD"],
    ["Haiti", "US Dollar", "HTG"],
    ["Holy See", "Euro", "EUR"],
    ["Honduras", "Lempira", "HNL"],
    ["Hong Kong", "Hong Kong Dollar", "HKD"],
    ["Hungary", "Forint", "HUF"],
    ["Iceland", "Iceland Krona", "ISK"],
    ["India", "Indian Rupee", "INR"],
    ["Indonesia", "Rupiah", "IDR"],
    ["Iran", "Iranian Rial", "IRR"],
    ["Iraq", "Iraqi Dinar", "IQD"],
    ["Ireland", "Euro", "EUR"],
    ["Israel", "New Israeli Sheqel", "ILS"],
    ["Italy", "Euro", "EUR"],
    ["Jamaica", "Jamaican Dollar", "JMD"],
    ["Japan", "Yen", "JPY"],
    ["Jordan", "Jordanian Dinar", "JOD"],
    ["Kazakhstan", "Tenge", "KZT"],
    ["Kenya", "Kenyan Shilling", "KES"],
    ["Kiribati", "Australian Dollar", "AUD"],
    ["Korea(North Korea)", "North Korean Won", "KPW"],
    ["Korea(South Korea)", "Won", "KRW"],
    ["Kuwait", "Kuwaiti Dinar", "KWD"],
    ["Kyrgyzstan", "Som", "KGS"],
    ["Lao", "Kip", "LAK"],
    ["Latvia", "Euro", "EUR"],
    ["Lebanon", "Lebanese Pound", "LBP"],
    ["Lesotho", "Loti ", "LSL"],
    ["Liberia", "Liberian Dollar", "LRD"],
    ["Libya", "Lybian Dinar", "LYD"],
    ["Liechtenstein", "Swiss Franc", "CHF"],
    ["Lithuania", "Euro", "LTL"],
    ["Luxembourg", "Euro", "EUR"],
    ["Macau", "Macanese Pataca", "MOP"],
    ["Macedonia,Rep.of", "Macedonian Denar", "MKD"],
    ["Madagascar", "Malagasy Franc", "MGF"],
    ["Malawi", "Kwacha", "MWK"],
    ["Malaysia", "Malaysian Ringgit", "MYR"],
    ["Maldives", "Rufiyaa", "MVR"],
    ["Mali", "CFA Franc BCEAO", "CFA"],
    ["Malta", "Maltese Lira", "MTL"],
    ["Marshall Islands", "US Dollar", "USD"],
    ["Martinique", "Euro", "EUR"],
    ["Mauritania", "Ouguiya", "MRO"],
    ["Mauritius", "Mauritius Rupee", "MUR"],
    ["Mayotte", "Euro", "EUR"],
    ["Mexico", "Mexican Peso", "MXN"],
    ["Micronesia, Federal States of", "US Dollar", "USD"],
    ["Moldova, Republic of", "Moldovan Leu", "MDL"],
    ["Monaco", "Euro", "EUR"],
    ["Mongolia", "Mongolia Tughrik", "MNT"],
    ["Montenegro", "Euro", "EUR"],
    ["Montserrat", "East Caribbean Dollar", "XCD"],
    ["Morocco", "Moroccan Dirham", "MAD"],
    ["Mozambique", "Mozambican Metical", "MZM"],
    ["Myanmar", "Burmese Kyat", "MMK"],
    ["Namibia", "Namibia Dollar", "NAD"],
    ["Nauru", "Australian Dollar", "AUD"],
    ["Nepal", "Nepalese Rupee", "NPR"],
    ["Netherlands", "Euro", "EUR"],
    [
        "Netherlands Antilles,Curaçao, Sint Maarten",
        "Netherlands Antilles Guilder",
        "ANG",
    ],
    ["New Caledonia", "CFP Franc", "XPF"],
    ["New Zealand", "New Zealand Dollar", "NZD"],
    ["Nicaragua", "Nicaraguan Córdoba ", "NIO"],
    ["Niger", "West African CFA Franc", "CFA"],
    ["Nigeria", "Nigerian Naira", "NGN"],
    ["Niue", "New Zealand Dollar", "NZD"],
    ["Northern Mariana Islands", "US Dollar", "USD"],
    ["Norway", "Norwegian Krone", "NOK"],
    ["Oman", "Omani Rial", "OMR"],
    ["Pakistan", "Pakistan Rupee", "PKR"],
    ["Palau", "US Dollar", "USD"],
    ["State of Palestine", "Egyptian Pound", "EGP"],
    ["State of Palestine", "Israeli New Shekel", "ILS"],
    ["State of Palestine", "Jordanian Dinar", "JOD"],
    ["Panama", "Panamanian Balboa", "PAB"],
    ["Panama", "US Dollar", "USD"],
    ["Papua New Guinea", "Papua New Guinean Kina", "PGK"],
    ["Paraguay", "Paraguayan Guarani", "PYG"],
    ["Peru", "Peruvian Sol", "PEN"],
    ["Philippines", "Philippine Peso", "PHP"],
    ["Pitcairn Island", "New Zealand Dollar", "NZD"],
    ["Poland", "Polish Zloty ", "PLN"],
    ["Portugal", "Euro", "EUR"],
    ["Puerto Rico", "US Dollar", "USD"],
    ["Qatar", "Qatari Rial", "QAR"],
    ["Reunion Island", "Euro", "EUR"],
    ["Romania", "Leu", "ROL"],
    ["Russian Federation", "Russian Ruble", "RUR"],
    ["Rwanda", "Rwanda Franc", "RWF"],
    ["Saint Helena", "Saint Helena Pound", "SHP"],
    ["Saint Kitts and Nevis", "East Caribbean Dollar", "XCD"],
    ["Saint Lucia", "East Caribbean Dollar", "XCD"],
    ["Saint Vincent and the Grenadines", "East Caribbean Dollar", "XCD"],
    ["Samoa", "Tala", "WST"],
    ["San Marino", "Euro", "EUR"],
    ["Sao Tome and Principe", "Dobra", "STD"],
    ["Saudi Arabia", "Saudi Riyal", "SAR"],
    ["Senegal", "CFA Franc BCEAO", "CFA"],
    ["Serbia", "Serbian Dinar", "CSD"],
    ["Seychelles", "Seychelles Rupee", "SCR"],
    ["Sierra Leone", "Leone", "SLL"],
    ["Singapore", "Singapore Dollar", "SGD"],
    ["Slovakia", "Euro ", "EUR"],
    ["Slovenia", "Euro ", "EUR"],
    ["Solomon Islands", "Solomon Islands Dollar", "SBD"],
    ["Somalia", "Somali Shilling", "SOS"],
    ["South Africa", "Rand", "ZAR"],
    ["South Sudan", "South Sudanese pound", "SSP"],
    ["Spain", "Euro", "EUR"],
    ["Sri Lanka", "Sri Lanka Rupee", "LKR"],
    ["Sudan", "Sudanese Dinar ", "SDD"],
    ["Suriname", "Suriname Guilder", "SRG"],
    ["Swaziland", "Lilangeni", "SZL"],
    ["Sweden", "Swedish Krona", "SEK"],
    ["Switzerland", "Swiss Franc", "CHF"],
    ["Syrian Arab Republic", "Syrian Pound", "SYP"],
    ["Taiwan, Republic of China", "New Taiwan Dollar", "TWD"],
    ["Tajikistan", "Somoni", "TJS"],
    ["Tanzania", "Tanzanian Shilling", "TZS"],
    ["Thailand", "Thai Baht", "THB"],
    ["Timor Leste", "US Dollar", "USD"],
    ["Togo", "CFA Franc BCEAO", "CFA"],
    ["Tokelau", "New Zealand Dollar", "NZD"],
    ["Tonga", "Paʻanga", "TOP"],
    ["Trinidad and Tobago", "Trinidad and Tobago Dollar", "TTD"],
    ["Tunisia", "Tunisian Dinar", "TND"],
    ["Turkey", "Yeni Türk Liras", "TRY"],
    ["Turkmenistan", "Manat", "TMM"],
    ["Turks and Caicos Islands", "US Dollar", "USD"],
    ["Tuvalu", "Australian Dollar", "AUD"],
    ["Uganda", "Uganda Shilling", "UGX"],
    ["Ukraine", "Ukrainian Hryvnia", "UAH"],
    ["United Arab Emirates", "UAE Dirham", "AED"],
    ["United Kingdom", "Pound Sterling", "GBP"],
    ["United States", "US Dollar", "USS"],
    ["Uruguay", "Uruguayan Peso", "UYU"],
    ["Uzbekistan", "Uzbekistan Sum", "UZS"],
    ["Vanuatu", "Vanuatu Vatu", "VUV"],
    ["Vatican City State", "Euro", "EUR"],
    ["Venezuela", "Venezuelan Bolívar", "VEF"],
    ["Vietnam", "Vietnamese Dong", "VND"],
    ["Virgin Islands", "US Dollar", "USD"],
    ["Virgin Islands", "US Dollar", "USD"],
    ["Wallis and Futuna Islands", "CFP Franc", "XPF"],
    ["Western Sahara", "Moroccan Dirham", "MAD"],
    ["Yemen", "Yemeni Rial", "YER"],
    ["Zambia", "Zambian Kwacha", "ZMW"],
    ["Zimbabwe", "Zimbabwe Dollar", "ZWD"],
]
